---
# This script contains commands to enable modules that are specified in configuration.
# TODO: Add "--root={{ docroot }}"
- name: Enable general modules
  shell: "{{ php_env_vars }} drush -y en {{ item.name }}"
  when: item.status == true
  with_items: global_env.modules
# TODO: Add "--root={{ docroot }}"
- name: Enable environment specific modules
  shell: "{{ php_env_vars }} drush -y en {{ item.name }}"
  when: item.status == true
  with_items: env.modules
