---
- name: Sync files into docroot
  shell: "rsync -avz {{ workspace }}/sourcecode/{{ project_docroot_folder }}/ {{ server_docroot_folder }}/build{{ build_number }}"

- name: Folder permissions
  shell: "sudo chown -R www-data:jenkins {{ server_docroot_folder }}/build{{ build_number }}"
