---
### Old bash script.
#export PYTHONUNBUFFERED=1
#echo "===============" > ${WORKSPACE}/commentinfo.md
#cd new_pull_request
#sudo rsync -avz docroot/ /var/www/build${BUILD_NUMBER}
#cd /var/www/build${BUILD_NUMBER}
#sudo chown -R www-data:jenkins *
#ansible-playbook reinstall.yml -i 'localhost,' --connection=local --extra-vars "php_env_vars='APP_ENV=dev' mysql_user=root mysql_pass=root mysql_db=drupal${BUILD_NUMBER} drupal_folder=/var/www/build${BUILD_NUMBER} site_url=http://10.0.2.15/build${BUILD_NUMBER} pp_environment='default'"
#ansible-playbook sniffers.yml -i 'localhost,' --connection=local --extra-vars "workspace_root=${WORKSPACE} webroot=http://10.0.2.15/build${BUILD_NUMBER} source_hash=${ghprbActualCommit} target_branch=${ghprbTargetBranch} pr_workspace=${WORKSPACE}/new_pull_request"
#ansible-playbook tests.yml -i 'localhost,' --connection=local --extra-vars "workspace_root=${WORKSPACE} behat_base_url=http://10.0.2.15/build${BUILD_NUMBER} update_dependencies='yes' resources_path=${WORKSPACE}/new_pull_request//tests/behat/resources behat_drupal_root=/var/www/build${BUILD_NUMBER} behat_root=${WORKSPACE}/new_pull_request/tests/behat"
#sudo chown -R www-data:jenkins ../build${BUILD_NUMBER}

- hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    workspace: ./
    build_number: 1
    server_docroot_folder: /var/www
    project_docroot_folder: docroot
    php_env_vars: 'APP_ENV=dev'
    mysql_user: 'root'
    mysql_password: 'root'
    mysql_db: drupal{{ build_number }}
    drupal_folder: "{{ server_docroot_folder }}/build{{ build_number }}"
    site_url: "http://10.0.2.15/build{{ build_number }}"
    pp_environment: 'default'
    run_reinstall: true

  pre_tasks:
    - name: Create commentinfo.md
      shell: echo "===============" > {{ workspace }}/commentinfo.md

    # /var/www permissions should be for www-data:jenkins.
    # sudo chmod -R 777 /var/www
    - name: Sync files into docroot
      shell: "rsync -avz {{ workspace }}/sourcecode/{{ project_docroot_folder }}/ {{ server_docroot_folder }}/build{{ build_number }}"

    - name: Folder permissions
      shell: "sudo chown -R www-data:jenkins {{ server_docroot_folder }}/build{{ build_number }}"

  # TODO: convert tasks to Ansible format.
  tasks:
    - name: Run reinstall.yml
      include: "{{ workspace }}/sourcecode/{{ project_docroot_folder }}/reinstall.yml"

    - name: Folder permissions
      shell: "sudo chown -R www-data:jenkins {{ server_docroot_folder }}/build{{ build_number }}"
